name: Autobahn

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      node-version:
        default: '24'
        type: string
  pull_request:
    paths:
      - '.github/workflows/autobahn.yml'
      - 'lib/web/websocket/**'
      - 'test/autobahn/**'

permissions:
  contents: read

jobs:
  autobahn:
    name: Autobahn Test Suite
    runs-on: ubuntu-latest
    container: node:24
    services:
      fuzzingserver:
        image: crossbario/autobahn-testsuite:latest
        ports:
          - '9001:9001'
        options: --name fuzzingserver
        volumes:
          - ${{ github.workspace }}/test/autobahn/config:/config
          - ${{ github.workspace }}/test/autobahn/reports:/reports
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          clean: false
      
      - name: Restart Autobahn Server
        # Restart service after volumes have been checked out
        uses: docker://docker
        with:
          args: docker restart --time 0 --signal=SIGKILL fuzzingserver

      - name: Setup Node.js@${{ inputs.node-version }}
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ inputs.node-version }}

      - name: Run Autobahn Test Suite
        run: npm run test:websocket:autobahn
        env:
          FUZZING_SERVER_URL: ws://fuzzingserver:9001
          LOG_ON_ERROR: false

      - name: Report CI
        id: report-ci
        run: npm run test:websocket:autobahn:report
        env:
          FAIL_ON_ERROR: true
