name: Update Submodules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-wpt:
    name: Update Submodules
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Git Config
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Update WPT
        run: |
          git submodule update --init --recursive
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          base: main
          branch: submodules-update
          title: Update Submodules
          body: Automated update of the Submodules
          commit-message: "chore: update Submodules"
